title: Dejima Store Blog
description: Discover unique Japanese souvenirs and cultural insights
author: Dejima Store
email: your-email@dejima.store
baseurl: "/blog" # ブログをサブディレクトリで運用する場合
url: "https://yourusername.github.io"

# ビルド設定
markdown: kramdown
theme: minima # または選択したテーマ名
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ブログ設定
permalink: /:year/:month/:day/:title/
